name: Autobuild Armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 8 * * 5


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Initialization environment
        env:
         DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get -qq update
          apt-get -qq install git
        
      - name: Clone source code
        run: |
          git clone https://github.com/armbian/build.git armbian
          
      - name: Build 
        run: |
          cd armbian
          ./compile.sh \
            BOARD=lepotato \
            BRANCH=current \
            RELEASE=focal \
            KERNEL_ONLY=no \
            KERNEL_CONFIGURE=no \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no
        
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: framebuffer
          path: /__w/RM2-FB/RM2-FB/fb/dist/*
