name: Autobuild Armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 8 * * 5


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialization environment
        env:
         DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install git
        
      - name: Clone source code & Customize
        run: |
          git clone https://github.com/armbian/build.git armbian
          cp -rf customize.patch armbian/
          cd armbian
          patch -p1 < ./customize.patch

      - name: Compile 
        run: |
          ./compile.sh \
            BOARD=lepotato \
            BRANCH=current \
            RELEASE=focal \
            KERNEL_ONLY=no \
            KERNEL_CONFIGURE=no \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no
          cd output/images
          ls -al
          
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: Images
          path: /home/runner/work/Armbian/Armbian/armbian/output/images/*
