name: Autobuild Armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 8 * * 5


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialization environment
        env:
         DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install git
        
      - name: Clone source code & Customize
        run: |
          git clone https://github.com/armbian/build.git armbian
          cp -rf customize.patch armbian/
          cd armbian
          patch -p1 < ./customize.patch
          cat config/kernel/linux-meson64-current.config
