name: Autobuild Armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 8 * * 5


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialization Environment
        env:
         DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install git
        
      - name: Clone Source Code & Customize
        run: |
          git clone https://github.com/armbian/build.git armbian
          # cp -rf customize.patch armbian/
          cp -rf meson-gxl.conf armbian/config/sources/families/
          cp -rf BesTV-R3300L.conf armbian/config/boards/
          # cd armbian
          # patch -p1 < ./customize.patch

      - name: Compile 
        run: |
          cd armbian
          ./compile.sh \
            BOARD=BesTV-R3300L \
            BRANCH=current \
            RELEASE=focal \
            KERNEL_ONLY=no \
            KERNEL_CONFIGURE=no \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            PROGRESS_LOG_TO_FILE=yes
          
      - name: Upload Image & Logs
        uses: actions/upload-artifact@main
        with:
          name: Image & Logs
          path: |
            /home/runner/work/Armbian/Armbian/armbian/output/debug/*.log
            /home/runner/work/Armbian/Armbian/armbian/output/images/*
